# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.4.0"

Vagrant.configure("2") do |config|

  config.vm.box = "XXX"
  config.vm.box_check_update = false
  config.vm.hostname = "XXX"
  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: XXX, host: XXX, host_ip: "127.0.0.1"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "html", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "XXX-Ubuntu"
     vb.memory = "XXX"
  end

  # Install Apache with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y apache2 php tree
    systemctl enable apache2.service
    systemctl start apache2.service
  SHELL
end
